apiVersion: v1
kind: Service
metadata:
  name: api-demo-service
spec:
  selector:
    app: api-demo
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 4000  # Container port
      nodePort: 31000    # NodePort to expose externally
  type: NodePort
